spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ai_community_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root

logging:
  level:
    com.aicommunity: DEBUG
    org.springframework.web: DEBUG
    org.mybatis: DEBUG
